# >>> traceknot >>>
COPILOT_OTEL_ENABLED='true'
COPILOT_OTEL_ENDPOINT='http://127.0.0.1:4318'
COPILOT_OTEL_CAPTURE_CONTENT='true'
CLAUDE_CODE_ENABLE_TELEMETRY=1
CLAUDE_CODE_ENHANCED_TELEMETRY_BETA=1
CLAUDE_CODE_OTEL_CONTENT_MAX_LENGTH=4000000
OTEL_EXPORTER_OTLP_ENDPOINT='http://127.0.0.1:4318'
OTEL_EXPORTER_OTLP_TRACES_ENDPOINT='http://127.0.0.1:4318/v1/traces'
OTEL_EXPORTER_OTLP_LOGS_ENDPOINT='http://127.0.0.1:4318/v1/logs'
OTEL_EXPORTER_OTLP_TRACES_PROTOCOL='http/protobuf'
OTEL_EXPORTER_OTLP_LOGS_PROTOCOL='http/protobuf'
OTEL_EXPORTER_OTLP_PROTOCOL='http/protobuf'
OTEL_INSTRUMENTATION_GENAI_CAPTURE_MESSAGE_CONTENT='true'
OTEL_LOG_LEVEL='ALL'
OTEL_TRACES_EXPORTER=otlp
OTEL_LOGS_EXPORTER=otlp
OTEL_LOG_USER_PROMPTS=1
OTEL_LOG_ASSISTANT_RESPONSES=1
OTEL_LOG_TOOL_DETAILS=1
OTEL_LOG_TOOL_CONTENT=1
OTEL_LOG_RAW_API_BODIES=1
# <<< traceknot <<<
