# >>> traceknot >>>
export COPILOT_OTEL_ENABLED='true'
export COPILOT_OTEL_ENDPOINT='http://127.0.0.1:4318'
export COPILOT_OTEL_CAPTURE_CONTENT='true'
export CLAUDE_CODE_ENABLE_TELEMETRY=1
export CLAUDE_CODE_ENHANCED_TELEMETRY_BETA=1
export CLAUDE_CODE_OTEL_CONTENT_MAX_LENGTH=4000000
export OTEL_EXPORTER_OTLP_ENDPOINT='http://127.0.0.1:4318'
export OTEL_EXPORTER_OTLP_TRACES_ENDPOINT='http://127.0.0.1:4318/v1/traces'
export OTEL_EXPORTER_OTLP_LOGS_ENDPOINT='http://127.0.0.1:4318/v1/logs'
export OTEL_EXPORTER_OTLP_TRACES_PROTOCOL='http/protobuf'
export OTEL_EXPORTER_OTLP_LOGS_PROTOCOL='http/protobuf'
export OTEL_EXPORTER_OTLP_PROTOCOL='http/protobuf'
export OTEL_INSTRUMENTATION_GENAI_CAPTURE_MESSAGE_CONTENT='true'
export OTEL_LOG_LEVEL='ALL'
export OTEL_TRACES_EXPORTER=otlp
export OTEL_LOGS_EXPORTER=otlp
export OTEL_LOG_USER_PROMPTS=1
export OTEL_LOG_ASSISTANT_RESPONSES=1
export OTEL_LOG_TOOL_DETAILS=1
export OTEL_LOG_TOOL_CONTENT=1
export OTEL_LOG_RAW_API_BODIES=1
# <<< traceknot <<<
